name: build

on:
  workflow_dispatch:
jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          java: 17
          arch: x64
          runner: windows-latest
        - os: windows-latest
          java: 17
          arch: arm64
          runner: windows-11-arm
        - os: macos-latest
          java: 17
          arch: x64
          runner: macos-15-intel
    runs-on: ${{ matrix.runner }}
    env:
      MAVEN_OPTS: "-Djava.awt.headless=true"
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK 17
      uses: actions/setup-java@v5.7.0
      with:
        java-version: '${{ matrix.java }}'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build project with Maven
      run: mvn -T 4 --batch-mode verify -P enableCheckStyle
